### ISSUE TITLE
您好，我转换失败了，得到了这个结果

### ISSUE THREAD

**Issue by JimXu1989** [FjjRichard/roLabelImgV2#1]
running with lxml.etree
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/home/xss/SoftWare/roLabelImgV2-main/roLabelImg.py", line 639, in convertbt
    convert.convert(self.sl.value()/100.0)
  File "/home/xss/SoftWare/roLabelImgV2-main/libs/convertCoco.py", line 124, in convert
    segmentation = self.get_and_check(obj,'segmentation',1)
  File "/home/xss/SoftWare/roLabelImgV2-main/libs/convertCoco.py", line 23, in get_and_check
    raise NotImplementedError('Can not find %s in %s.'%(name, root.tag))
NotImplementedError: Can not find segmentation in object.

**Comment by JimXu1989** [comment]
原来是四点标注，现在改成角度和长宽了
   <type>robndbox</type>
    <name>n</name>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <robndbox>
      <cx>2672.1522</cx>
      <cy>1101.0652</cy>
      <w>513.0</w>
      <h>657.0</h>
      <angle>0.142163</angle>
    </robndbox>

**Comment by FjjRichard** [comment]
> 原来是四点标注，现在改成角度和长宽了 robndbox n Unspecified 0 0 2672.1522 1101.0652 513.0 657.0 0.142163

是的，只能转换带角度的四点标注
